# Default values for descheduler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: us.gcr.io/k8s-artifacts-prod/descheduler/descheduler
  tag: v0.10.0
  pullPolicy: IfNotPresent

schedule: "*/30 * * * *"

cmdOptions:
  v: 4
  max-pods-to-evict-per-node: 10

deschedulerPolicy:
  strategies:
    RemoveDuplicates:
      enabled: false
    LowNodeUtilization:
      enabled: true
      params:
        nodeResourceUtilizationThresholds:
          thresholds:
            cpu: 20
            memory: 20
            pods: 20
          targetThresholds:
            cpu: 50
            memory: 50
            pods: 50
    RemovePodsViolatingInterPodAntiAffinity:
      enabled: true
    RemovePodsViolatingNodeAffinity:
      enabled: true
      params:
        nodeAffinityType:
        - requiredDuringSchedulingIgnoredDuringExecution
    RemovePodsViolatingNodeTaints:
      enabled: true

rbac:
  # Specifies whether RBAC resources should be created
  create: true

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true
  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name:
